name: casher
description: Casher application. Save your money with Casher!

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^3.2.4

  # Bottom navigation
  salomon_bottom_bar: ^3.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # Firebase core, auth and cloud store
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  firebase_analytics: ^5.0.2
  cloud_firestore: ^3.1.10
  provider: ^6.0.2

  # Animated splash screen
  animated_splash_screen: ^1.2.0

  # Database connection
  drift: ^1.5.0
  sqlite3_flutter_libs: ^0.5.5
  path_provider: ^2.0.9
  path: ^1.8.0
  ffi: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^3.2.3

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

  # Tools for database works
  drift_dev: ^1.5.2
  build_runner: ^2.1.8

flutter:
  uses-material-design: true

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-SemiBold.ttf

  assets:
    - assets/images/casher.png
    - assets/images/splash.jpg
    - assets/images/card/chip.png
    - assets/images/card/card_operator.png
    - assets/images/banknote/dollar.png
    - assets/icons/app_icon.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"